name: Build and Push Latest Docker Image to GHCR

on:
  push:
    branches:
      - main

jobs:
  push_to_registry:
    name: Build and Push Latest Docker Image to GHCR
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push the latest Steel Browser API image
        run: |
          docker build -t ghcr.io/uamohq/steel-browser-api:latest ./api -f ./api/Dockerfile
          docker push ghcr.io/uamohq/steel-browser-api:latest
      - name: Build and push the latest Steel Browser UI image
        run: |
          docker build -t ghcr.io/uamohq/steel-browser-ui:latest ./ui -f ./ui/Dockerfile
          docker push ghcr.io/uamohq/steel-browser-ui:latest
